spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/order_db
    username: root
    password: root
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:

      schema-locations: classpath:/init.sql